function draw_band_structure(eigenval_file, doscar_file, poscar_file, kpoints_file, n_band)
%draw band structure of a system
%   draw_band_structure(eigenval_file, doscar_file, poscar_file, kpoints_file, n_band)
%   eigenval_file: the path of EIGENVAL file
%   doscar_file:   the path of DOSCAR file
%   poscar_file:   the path of POSCAR file
%   kpoints_file:  the path of KPOINTS file, note that kpoints file must be
%   generated by ALFOW format.
%   n_band:        the band number you want to plot
% 
%   Examples:
%
%       eigenval_file = 'EIGENVAL';doscar_file = 'DOSCAR';
%       poscar_file = 'POSCAR';kpoints_file = 'KPONTS';n_band = 10;
%       draw_band_structure(eigenval_file, doscar_file, poscar_file, kpoints_file, n_band)
%
%
%   See also draw_band_structure_dos, draw_dos_element, draw_dos_pdos


[energy, kpoint] = read_eigenval(eigenval_file);
if length(energy) == 1
    Efermi = get_fermi_from_doscar(doscar_file);
    energy_up = energy{1} - Efermi;
    [rec_k, sys_name] = read_recip(poscar_file);
    sys_name = deblank(sys_name);
    for ii = 2:size(kpoint,1)
        kpoint(ii, 5) = norm((kpoint(ii-1,1:3)-kpoint(ii,1:3)) * rec_k);
    end
    kpoint(:,5) = cumsum(kpoint(:,5));
    q1 = find(energy_up(:,1)>0);
    if mod(n_band,2) == 0
        low_lim = n_band/2;
        up_lim = n_band/2-1;
    else
        low_lim = floor(n_band/2);
        up_lim = floor(n_band/2);
    end
    [hsp, hsp_label, node] = read_high_sym_point(kpoints_file);
    energy_up = energy_up - max(energy_up(q1(1)-1,:));
    energy_gap = min(energy_up(q1(1),:)) - max(energy_up(q1(1)-1,:));
    figure
    plot_band(kpoint, energy_up(q1(1)-low_lim:q1(1)+up_lim,:), hsp, hsp_label, node, sys_name, energy_gap)
else
    Efermi = get_fermi_from_doscar(doscar_file);
    energy_up = energy{1} - Efermi;
    energy_down = energy{2} - Efermi;
    [rec_k, sys_name] = read_recip(poscar_file);
    sys_name = deblank(sys_name);
    for ii = 2:size(kpoint,1)
        kpoint(ii, 5) = norm((kpoint(ii-1,1:3)-kpoint(ii,1:3)) * rec_k);
    end
    kpoint(:,5) = cumsum(kpoint(:,5));
    q1 = find(energy_up(:,1)>0);
    if mod(n_band,2) == 0
        low_lim = n_band/2;
        up_lim = n_band/2-1;
    else
        low_lim = floor(n_band/2);
        up_lim = floor(n_band/2);
    end
    %
    [hsp, hsp_label, node] = read_high_sym_point(kpoints_file);
    energy_gap = min(energy_up(q1(1),:)) - max(energy_up(q1(1)-1,:));
    figure
    plot_band(kpoint, energy_up(q1(1)-low_lim:q1(1)+up_lim,:), hsp, hsp_label, node, sys_name, energy_gap)
    
    q1 = find(energy_down(:,1)>0);
    if mod(n_band,2) == 0
        low_lim = n_band/2;
        up_lim = n_band/2-1;
    else
        low_lim = floor(n_band/2);
        up_lim = floor(n_band/2);
    end
    energy_gap = min(energy_down(q1(1),:)) - max(energy_down(q1(1)-1,:));
    figure
    plot_band(kpoint, energy_down(q1(1)-low_lim:q1(1)+up_lim,:), hsp, hsp_label, node, sys_name, energy_gap)
    
end