function draw_band_structure_dos(eigval_file, dos_file, pos_file, kpts_file, have_pdos)
%draw band structure and dos of a system, except for magnetism system
%   draw_band_structure_dos(eigval_file, dos_file, pos_file, kpts_file, have_pdos)
%   eigval_file: the path of EIGENVAL file
%   dos_file:   the path of DOSCAR file
%   pos_file:   the path of pos file
%   kpts_file:  the path of KPOINTS file, note that kpoints file must be
%   generated by ALFOW format.
%   have_pdos: true if you have set LORBIT=11 in INCAR; 
%              false else.
%
%   Examples:
%
%       pat = 'band';
%       have_pdos = true;
%       eigval_file = fullfile(pat, 'EIGENVAL');
%       dos_file = fullfile(pat, 'DOSCAR');
%       pos_file = fullfile(pat, 'POSCAR');
%       kpts_file = fullfile(pat, 'KPOINTS');
%       draw_band_structure_dos(eigval_file, dos_file, pos_file, kpts_file, have_pdos)
%
%
%   See also draw_band_structure, draw_dos_element, draw_dos_pdos


[energy, kpoint] = read_eigenval(eigval_file);
energy = energy{1};
[rec_k, sys_name] = read_recip(pos_file);
sys_name = deblank(sys_name);
for ii = 2:size(kpoint,1)
    kpoint(ii, 5) = norm((kpoint(ii-1,1:3)-kpoint(ii,1:3)) * rec_k);
end
kpoint(:,5) = cumsum(kpoint(:,5));
tmp_occupy = energy(:,2:2:end);
tmp_mean_occupy_up = mean(tmp_occupy,2);

q_up = find(abs(diff(tmp_mean_occupy_up))>0.8);
cbm_up = energy(q_up+1,1:2:end);
vbm_up = energy(q_up,1:2:end);

[hsp, hsp_label, node] = read_high_sym_point(kpts_file);
energy_gap = min(cbm_up) - max(vbm_up);
energy = energy - max(vbm_up);

figure
h1 = subplot(1,2,1);
h1_pos = get(h1,'position');
set(h1,'position',[h1_pos(1)+0.05 h1_pos(2:4)])
plot_band(kpoint, energy(:,1:2:end), hsp, hsp_label, node, sys_name, energy_gap,'k')

screen_size = get(0,'screensize');
set(gcf, 'Position',[0.8*screen_size(1:2)+100 0.8*screen_size(3:4)])

fid = fopen(dos_file, 'rt');
k = 1;
while feof(fid) == 0
    tline = fgetl(fid);
    if k == 1
        s1 = str2num(tline);
    end
    if k == 6
        s = str2num(tline);
        break
    end
    k = k + 1;
end
fclose(fid);

h1_pos = get(h1,'position');
h2 = subplot(1,2,2);
set(h2, 'position', [h1_pos(1)+h1_pos(3) h1_pos(2) h1_pos(3) h1_pos(4)])
if have_pdos
    fid = fopen(dos_file, 'rt');
    FormatString=repmat('%f ',1,3);
    sum_dos = cell2mat(textscan(fid,FormatString,s(3),'HeaderLines',6));
    FormatString = repmat('%f ',1,10);
    p_dos = zeros(s(3), 10);
    for ii = 1:s1(1)
        temp = cell2mat(textscan(fid,FormatString,s(3),'HeaderLines',2));
        p_dos(:,2:end) = p_dos(:,2:end) + temp(:,2:end);
    end
    fclose(fid);
    p_dos(:,1) = sum_dos(:,1) - max(vbm_up);
    plot(sum_dos(:,2), p_dos(:,1), 'r','LineWidth', 3);hold on
    plot(p_dos(:,2), p_dos(:,1), 'm','LineWidth', 3);hold on
    plot(p_dos(:,3)+p_dos(:,5)+p_dos(:,4),p_dos(:,1), 'b','LineWidth', 3)
    plot(sum(p_dos(:,6:10),2), p_dos(:,1), 'g','LineWidth', 3);
    x_value = get(gca, 'XTick');
    y_value = get(h1,'YTick');
    axis([x_value(1) x_value(end) y_value(1) y_value(end)])
    set(gca,'YTick', [], 'YTickLabel', []);
    sum_dos(:,1) = sum_dos(:,1)- max(vbm_up);
    [~,ind] = min(abs(sum_dos(:,3) - q_up*2));
    sum_dos = sum_dos(1:ind+1,:);
    patch([sum_dos(:,2);flipud(zeros(size(sum_dos,1),1))],...
        [sum_dos(:,1);flipud(sum_dos(:,1))],...
        [45 48 52]/255,...
        'FaceA',.2,'EdgeA',0);
    legend('total','s-orbit','p-orbit','d-orbit')
    set(gca,'XTick', [], 'XTickLabel', []);
else
    fid = fopen(dos_file, 'rt');
    FormatString=repmat('%f ',1,5);
    sum_dos = cell2mat(textscan(fid,FormatString,s(3),'HeaderLines',6));
    if sum(sum(isnan(sum_dos))) == 0; ispin = 1;else ispin = 0;end
    fclose(fid);
    if ispin; FormatString=repmat('%f ',1,5);
    else FormatString=repmat('%f ',1,3);end
    fid = fopen(dos_file, 'rt');
    sum_dos = cell2mat(textscan(fid,FormatString,s(3),'HeaderLines',6));
    fclose(fid);
    y_value = get(h1,'YTick');
    sum_dos(:,1) = sum_dos(:,1)-max(vbm_up);
    q1 = find(sum_dos(:,1) < y_value(end));q2 = find(sum_dos(:,1)>y_value(1));
    q = intersect(q1,q2);
    sum_dos = sum_dos(q,:);
    plot(sum_dos(:,2), sum_dos(:,1),'LineWidth', 3)
    hold on
    [~,ind] = min(abs(sum_dos(:,3) - q_up*2));
    sum_dos = sum_dos(1:ind+1,:);
    patch([sum_dos(:,2);flipud(zeros(size(sum_dos,1),1))],...
        [sum_dos(:,1);flipud(sum_dos(:,1))],...
        [45 48 52]/255,...
        'FaceA',.2,'EdgeA',0)
    set(gca,'YTick', [], 'YTickLabel', []);
    set(gca,'XTick', [], 'XTickLabel', []);
    legend('Total DOS')
    title('DOS')
    set(gca,'XTick', [], 'XTickLabel', []);
end
